# Use root/password as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    #TODO: Enable it after auth setup
    #environment:
    #MONGO_INITDB_ROOT_USERNAME: root
    #MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_db_dir:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./ssl/test-ca.pem:/etc/ssl/test-ca.pem
      - ./ssl/test-client.pem:/etc/ssl/test-client.pem
      - ./ssl/test-server1.pem:/etc/ssl/test-server1.pem
      
    command: [-f, /etc/mongod.conf]

    ports:
      - 27017:27017
    logging:
        driver: "json-file"
        options:
            max-size: "2m"
            max-file: "2"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ./ssl/dump/mongodb-test-ca.crt:/etc/ssl/mongodb-test-ca.crt:ro
      - ./config.js:/node_modules/mongo-express/config.js:ro
    environment:
      ME_CONFIG_MONGODB_CA_FILE: /etc/ssl/mongodb-test-ca.crt
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: root
      #ME_CONFIG_MONGODB_SERVER: ''

    links:
      - "mongo"

    logging:
        driver: "json-file"
        options:
            max-size: "2m"
            max-file: "2"

